### ISSUE TITLE
undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

### ISSUE THREAD

**Issue by sebastianopazo1** [SHI-Labs/OneFormer#101]
Hi! I encountered the next error when trying to run the project.
Traceback (most recent call last):
  File "/home/seba/Documents/OneFormer/demo/demo.py", line 26, in <module>
    from oneformer import (
  File "/home/seba/Documents/OneFormer/demo/../oneformer/__init__.py", line 2, in <module>
    from . import modeling
  File "/home/seba/Documents/OneFormer/demo/../oneformer/modeling/__init__.py", line 5, in <module>
    from .pixel_decoder.msdeformattn import MSDeformAttnPixelDecoder
  File "/home/seba/Documents/OneFormer/demo/../oneformer/modeling/pixel_decoder/msdeformattn.py", line 23, in <module>
    from .ops.modules import MSDeformAttn
  File "/home/seba/Documents/OneFormer/demo/../oneformer/modeling/pixel_decoder/ops/modules/__init__.py", line 10, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/seba/Documents/OneFormer/demo/../oneformer/modeling/pixel_decoder/ops/modules/ms_deform_attn.py", line 25, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/seba/Documents/OneFormer/demo/../oneformer/modeling/pixel_decoder/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/seba/Documents/OneFormer/demo/../oneformer/modeling/pixel_decoder/ops/functions/ms_deform_attn_func.py", line 23, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/seba/.local/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

**Comment by cz-cz** [comment]
hi,l tried this,and the problem is solved.
```
git clone https://github.com/facebookresearch/Mask2Former.git
cd Mask2Former
pip install -r requirements.txt
cd mask2former/modeling/pixel_decoder/ops
sh make.sh
```
