### ISSUE TITLE
AssertionError: Checkpoint dinat_large_in22k_in1k_384_11x11.pkl not found!

### ISSUE THREAD

**Issue by sahityabonumaddi** [SHI-Labs/OneFormer#36]
[03/21 22:37:19 d2.data.build]: Using training sampler TrainingSampler
[03/21 22:37:19 d2.data.common]: Serializing 20210 elements to byte tensors and concatenating them all ...
[03/21 22:37:19 d2.data.common]: Serialized dataset takes 18.42 MiB
[03/21 22:37:19 fvcore.common.checkpoint]: [Checkpointer] Loading from dinat_large_in22k_in1k_384_11x11.pkl ...
Traceback (most recent call last):
  File "train_net.py", line 435, in <module>
    launch(
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 424, in main
    trainer.resume_or_load(resume=args.resume)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint dinat_large_in22k_in1k_384_11x11.pkl not found!

Similar errors popped when I try with other backbones too, I have no idea why, Any help would be great, Thanks in advance!

**Comment by praeclarumjj3** [comment]
Please make sure you download the pretrained backbone weights before training. More info [here](https://github.com/SHI-Labs/OneFormer/tree/main/tools#download-pretrained-weights).

```bash
wget https://shi-labs.com/projects/dinat/checkpoints/imagenet1k/dinat_large_in22k_in1k_384_11x11.pth
python tools/convert-pretrained-nat-model-to-d2.py dinat_large_in22k_in1k_384_11x11.pth dinat_large_in22k_in1k_384_11x11.pkl
```
