### ISSUE TITLE
ERROR [04/29 21:09:11 d2.checkpoint.c2_model_loading]: Ambiguity found for res5.0.conv1.norm.bias in checkpoint!It matches at least two keys in the model (roi_heads.res5.0.conv1.norm.bias and backbone.res5.0.conv1.norm.bias).

### ISSUE THREAD

**Issue by sahityabonumaddi** [SHI-Labs/OneFormer#52]
I was stuck at this error, any help would be great ! @praeclarumjj3 

[04/29 21:09:11 oneformer.data.dataset_mappers.oneformer_unified_dataset_mapper]: [OneFormerUnifiedDatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=..., max_size=2048, sample_style='choice'), RandomCrop_CategoryAreaConstraint(crop_type='absolute', crop_size=[1024, 1024], single_category_max_area=1.0, ignored_category=255), <detectron2.projects.point_rend.color_augmentation.ColorAugSSDTransform object at 0x7fa072dcfe20>, RandomFlip()]
[04/29 21:09:11 d2.data.build]: Using training sampler TrainingSampler
[04/29 21:09:11 d2.data.common]: Serializing 6000 elements to byte tensors and concatenating them all ...
[04/29 21:09:11 d2.data.common]: Serialized dataset takes 7.08 MiB
[04/29 21:09:11 fvcore.common.checkpoint]: [Checkpointer] Loading from detectron2://ImageNetPretrained/torchvision/R-50.pkl ...
[04/29 21:09:11 fvcore.common.checkpoint]: Reading a file from 'torchvision'
ERROR [04/29 21:09:11 d2.checkpoint.c2_model_loading]: Ambiguity found for res5.0.conv1.norm.bias in checkpoint!It matches at least two keys in the model (roi_heads.res5.0.conv1.norm.bias and backbone.res5.0.conv1.norm.bias).
Traceback (most recent call last):
  File "train_net.py", line 435, in <module>
    launch(
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 424, in main
    trainer.resume_or_load(resume=args.resume)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 156, in load
    incompatible = self._load_model(checkpoint)
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 97, in _load_model
    checkpoint["model"] = align_and_update_state_dicts(
  File "/home/iit29/anaconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/checkpoint/c2_model_loading.py", line 287, in align_and_update_state_dicts
    raise ValueError("Cannot match one checkpoint key to multiple keys in the model.")
ValueError: Cannot match one checkpoint key to multiple keys in the model.

I'm using custom dataset for panoptic segmentation.
wrote register file, config file , used oneformer_unified_dataset_mapper, COCOPanopticEvaluator.

Thanks in advance !

**Comment by leserein17** [comment]
I got the same question. Do you have the solution to solve it?
